name: Update Tool Ranking

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  update-ranking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch Ranking from GAS
      env:
        GAS_URL: ${{ secrets.GAS_URL }} # GitHubのSecretsにGASのURLを登録してね
      run: |
        curl -L "$GAS_URL" -o ranking.json

    - name: Commit and Push ranking.json
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ranking.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update ranking.json" && git push)
